### ISSUE TITLE
Support Markdown

### ISSUE THREAD

**Issue by fbrnc** [mzeis/Mzeis_Documentation#1]
I love markdown and I'd love to see an option where you could create pages using markdown (in addition to the wysiwyg editor)

**Comment by mzeis** [comment]
In fact, @tobi-pb has created an extension at the same time as me that does just that: https://github.com/code-x/Docview

We also thought about combining the two modules. I'd love to do that but at first glance I didn't see how we could merge them the best way. I'm open to suggestions how we could to that!

**Comment by mzeis** [comment]
It's a basic support, but it is a start.

**Comment by mzeis** [comment]
This was released in [v1.1.0](https://github.com/mzeis/Mzeis_Documentation/releases/tag/v1.1.0).
